# Server
SERVER_PORT=8081
  
  # Keycloak
KEYCLOAK_HOST=localhost:8080
KEYCLOAK_REALM=my-realm
KEYCLOAK_CLIENT_ID=individuals-api
KEYCLOAK_CLIENT_SECRET=your-client-secret-here
KEYCLOAK_ADMIN_EMAIL=admin@mail.ru
KEYCLOAK_ADMIN_PASSWORD=1234
KEYCLOAK_BASE_URL=http://localhost:8080
KEYCLOAK_TOKEN_ENDPOINT=/realms/my-realm/protocol/openid-connect/token
  
  # Logging
LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG
LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY_OAUTH2=DEBUG
  
  # Docker Compose
DOCKER_COMPOSE_ENABLED=false